name: xts
channels:
  - defaults
dependencies:
    - python=3.7
    - pytorch::pytorch=1.3.1
    - pytorch::torchvision=0.4.2
    - cudatoolkit=10.0
    - numpy
    - matplotlib
    - scipy
    - conda
